import Header from "@/layout/header";
import "./globals.css";
import { kanit, rubik_font } from "./fonts";
import Footer from "@/layout/footer";

const kanit_fonts = kanit;
const rubik = rubik_font;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className} w-auto h-auto  `}>
        <Header kanit={kanit_fonts} />
        <main className="h-screen lg:w-full">
          <div className="snap-y snap-mandatory w-full h-full lg:h-screen  lg:w-full overflow-y-scroll">
            {children}
            <Footer kanit={kanit_fonts}></Footer>
          </div>
        </main>
      </body>
    </html>
  );
}
